spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/a0a70b2c-dc9a-4b05-aeb0-f4ea14473036/v2.0
        registration:
          azure-dev:
            provider: azure
            client-id: 1f49bb19-9bd5-40e2-9cbd-8d9bd8ceb5b1
            client-secret: wAr8Q~7yGFAPTD4u2NCFJyYBz0wWOo7QvT8jfaA0         
            scope:
            - openid
            - email
            - profile
